name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gorilla-ubuntu:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: shards install

    - name: Build Gorilla Programming Language
      run: crystal build src/gorilla.cr -o gorilla

  gorilla-macos:

    runs-on: macos-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: shards install

    - name: Build Gorilla Programming Language
      run: crystal build src/gorilla.cr -o gorilla